### PR TITLE
Add feature dynamically updating m3u8 and .ts source file

### PR DESCRIPTION
**Pull request by vaultec81**
Detailed in #12 
ping @moshisushi :)

### CODE REVIEW

**Comment by moshisushi** [comment]
Thanks! Will have a proper look at this over the weekend :)

A quick first observation tho: I'm not sure about ignoring the package-lock.json file. As far as I know, the lock file is supposed to be committed: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

**Comment by vaultec81** [comment]
Yeah I saw that too. I saw that it wasnt committed in the first place so I decided not to add it. Generally speaking I haven't seen it committed alot in other projects.

**Comment by vaultec81** [comment]
ping @moshisushi

**Comment by moshisushi** [comment]
@vaultec81 Sorry I've had family business to take care of and not had time to look into this. Would you like to be added as a collaborator to this repo?

**Comment by vaultec81** [comment]
@moshisushi No worries. and sure thing.

**Comment by moshisushi** [comment]
@vaultec81 Cheers! Do you have an npm alias as well please so I can add you there as well?

**Comment by vaultec81** [comment]
@moshisushi yes I do, the same as GitHub so vaultec81. Thanks.

**Comment by moshisushi** [comment]
@vaultec81 great, you're added! knock yourself out :)

**Comment by balgarath** [comment]
@vaultec81 was wondering if you have an example of this being used?  I'm trying to puzzle out using this for an hls livestream over ipfs

Thanks!

**Comment by vaultec81** [comment]
@balgarath Example use case would be in circumstances where you would want to actively update/live stream HLS chunks. Before this was merged, it was impossible to update a livestream on the fly. There still is a couple of things that need to be created for a full scale live streaming system to be viable. Eventual project to be worked on.

**Pull request merged**
