### PR TITLE
Replace Callbacks with Promises

### PR DESCRIPTION
**Pull request by tcyrus**
Use ES6 and Promise Chaining to remove nested callbacks and simplify code (since js-ipfs supports Promises). Also replaced usage of `ipfs.object`, since it's listed as a legacy API.

### CODE REVIEW

**Comment by vaultec81** [comment]
@moshisushi

**Comment by moshisushi** [comment]
Thanks for nudge @vaultec81! Really need to figure out why github isn't sending me email for new PRs :/ Will look at this asap.

**Comment by moshisushi** [comment]
Thanks @tcyrus! Looks like a step in the right direction, but didn't work for me (tested quickly with examples/basic_usage.html, which works fine when building from the commit prior to this merge).

Will have a look at some point this week and see what's going on, before pushing a new version to npm. Cheers.

**Comment by tcyrus** [comment]
Maybe the change on the last line broke it. I'm directly including the package via webpack, which might be the reason I'm not seeing the same errors.

**Comment by tcyrus** [comment]
@moshisushi Did some testing and confirmed that it was the last commit I made (https://github.com/moshisushi/hlsjs-ipfs-loader/pull/11/commits/af8dd70a01cd307b5966c87117dbbd69d501977b). Reverting the individual commit should resolve the issue. I'm also preparing a new PR with IPFS Companion support as well as the updated `aegir` if you want to wait.

**Comment by moshisushi** [comment]
All good, I can wait for the full PR :)

**Pull request merged**
