### PR TITLE
fix: upgrade for 0.36

### PR DESCRIPTION
**Pull request by alanshaw**
The IPLD dag-pb format changed in 0.36 to more closely follow it's serialized form.

See the release notes for more info https://github.com/ipfs/js-ipfs/issues/2024

### CODE REVIEW

**Comment by alanshaw** [comment]
ping @moshisushi - is it possible to get this merged and released?

**Comment by moshisushi** [comment]
Thanks @alanshaw! Something is wrong with my notification setup so totally missed this PR. Sorry about that! Will build a release asap.

**Comment by moshisushi** [comment]
https://www.npmjs.com/package/hlsjs-ipfs-loader/v/0.1.4 New version here

**Comment by alanshaw** [comment]
Thank you!

**Pull request merged**
